name: Labeler

on: [pull_request]

# This workflow will require write permissions on pull requests
# 1. Repository Settings -> Actions -> General -> Workflow permissions
#   Check "Read and write permissions"

permissions:
  contents: read
  pull-requests: write

jobs:
  labeler:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
