name: Run Test Suite

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  tests:
    name: Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          cache: npm

      - name: Install dependencies
        run: |
          set -xe
          npm i

      - name: Testing
        run: |
          set -xe
          npm run test

  synced:
    name: Ensure synced
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4.0.2
        with:
          cache: npm

      - name: Ensure synced
        run: |
          set -xe
          npm run sync:check

  # It is recommended to require this check to pass before merging a pull request
  check:
    if: always()
    name: Tests Successful
    runs-on: ubuntu-latest
    needs: [tests]

    steps:
      - name: Whether the whole test suite passed
        uses: re-actors/alls-green@v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
